apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: dev
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 50
  replicas: 7
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: spring
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: zeusmanor/zeus:100
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /web-app
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /web-app
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /web-app
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: spring-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: spring
  ports:
  - targetPort: 8080
    port: 80
    nodePort: 32000
